-- Geração de Modelo Fisico 
-- Sql ANSI 2003 - brModelo.
-- Author: Marlon Castro
-- Data: 22/03/2019 
-- Projeto de Banco de Dados
-- Sistema de Controle Patrimonial 

CREATE TABLE RES_RESPONSAVEL (
    RES_ID INT(9) PRIMARY KEY AUTO_INCREMENT,
    RES_MATRICULA INT(7) NOT NULL UNIQUE,
    RES_NOME VARCHAR(128) NOT NULL,
    CAR_ID INT(3)
)

CREATE TABLE CAR_CARGO (
    CAR_ID INT(3) PRIMARY KEY AUTO_INCREMENT,
    CAR_DESCRICAO VARCHAR(64) NOT NULL
)

CREATE TABLE RES_RESPONSAVEL_SETOR (
    RES_ID INT(9),
    SET_ID INT(3),
    RES_NU_PUBLICACAO INT(10) NOT NULL,
    RES_DT_INICIO_VIGENCIA DATE NOT NULL,
    RES_DT_FIM_VIGENCIA DATE NOT NULL,
    FOREIGN KEY(RES_ID) REFERENCES RES_RESPONSAVEL (RES_ID),
    FOREIGN KEY(SET_ID) REFERENCES SET_SETOR (SET_ID)
)

CREATE TABLE SET_SETOR (
    SET_ID INT(3) PRIMARY KEY AUTO_INCREMENT,
    SET_DESCRICAO VARCHAR(64) NOT NULL,
    SET_OBSERVACOES_GERAIS VARCHAR(256)
)

CREATE TABLE VAL_VALOR (
    VAL_COD_USUARIO INT(10),
    VAL_DH_ALTERACAO DATETIME NOT NULL,
    VAL_ID INT(10) PRIMARY KEY,
    VAL_VALOR FLOAT,
    VAL_ANO INT(4)
)

CREATE TABLE CAT_CATALOGO_EFISCO (
    CAT_ID INT(9) PRIMARY KEY AUTO_INCREMENT,
    CAT_CODIGO_ITEM INT(10) NOT NULL UNIQUE,
    CAT_DESCRICAO_ITEM VARCHAR(512) NOT NULL
)

CREATE TABLE INV_INVENTARUAL_ANUAL (
    INV_ID INT(5) PRIMARY KEY AUTO_INCREMENT,
    INV_PERIODO_FIM DATE NOT NULL,
    INV_PERIODO_INI DATE NOT NULL,
    INV_DATA_ENTREGA DATE NOT NULL,
    COM_ID INT(10) NOT NULL UNIQUE
)

CREATE TABLE CONTEM (
    INV_ID INT(5),
    ITE_ID INT(20),
    FOREIGN KEY(INV_ID) REFERENCES INV_INVENTARUAL_ANUAL (INV_ID)
)

CREATE TABLE DES_DESCARGA (
    DES_ID INT(5) PRIMARY KEY AUTO_INCREMENT,
    DES_COD_ENTIDADE_DOACAO INT(5) NOT NULL UNIQUE,
    DES_NOME_ENTIDADE_DOACAO VARCHAR(40) NOT NULL,
    COM_ID INT(10)
)

CREATE TABLE INC_INCLUSAO (
    INC_ID INT(5) PRIMARY KEY AUTO_INCREMENT,
    INC_COD_DOADOR INT(5) NOT NULL,
    INC_CPF_DOADOR INT(11) NOT NULL UNIQUE,
    INC_NOME_DOADOR VARCHAR(40) NOT NULL,
    COM_ID INT(10) NOT NULL 
)


CREATE TABLE COM_COMISSAO_DO_PROCESSO (
    COM_ID INT(10) PRIMARY KEY AUTO_INCREMENT,
    COM_DT_INSTITUICAO DATE NOT NULL,
    COM_NU_PORTARIA_DE_DESIGNACAO INT(10) NOT NULL,
    COM_NU_BOLETIM_INTERNO INT(6) NOT NULL
)

CREATE TABLE ITE_ITEM (
    ITE_ID INT(20) PRIMARY KEY AUTO_INCREMENT,
    ITE_DESCRICAO VARCHAR(40) NOT NULL
)

CREATE TABLE ITI_ITENS_EM_PROCESSO_INCLUSAO (
    ITE_CODIGO INT(20) PRIMARY KEY AUTO_INCREMENT,
    ITI_VALOR_NOTA FLOAT NOT NULL,
    ITI_DATA_NOTA DATE NOT NULL,
    INC_ID INT(11) NOT NULL,
    FOREIGN KEY(ITE_CODIGO) REFERENCES ITE_ITEM (ITE_ID),
    FOREIGN KEY(INC_ID) REFERENCES INC_INCLUSAO (INC_ID)
)

CREATE TABLE ITR_ITEM_RELACIONADO (
    ITE_ID INT(20) PRIMARY KEY AUTO_INCREMENT,
    ITR_NUM_LOTE VARCHAR(10) NOT NULL,
    FOREIGN KEY(ITE_ID) REFERENCES ITE_ITEM (ITE_ID)
)

CREATE TABLE ITE_ITEM_PARTICULAR (
    ITE_ID INT(20) PRIMARY KEY AUTO_INCREMENT,
    ITE_NOME_PROPRIETARIO VARCHAR(40) NOT NULL,
    FOREIGN KEY(ITE_ID) REFERENCES ITE_ITEM (ITE_ID)
)

CREATE TABLE TER_TERMO_DE_RESPONSABILIDADE (
    ITE_ID INT(20),
    SET_ID INT(3),
    TER_DT_EMISSAO_TERMO DATE NOT NULL,
    TER_NUM_TERMO_TRANSFERENCIA INT(6) NOT NULL,
    TER_DT_TRANSFERENCIA DATE NOT NULL,
    FOREIGN KEY(ITE_ID) REFERENCES ITE_ITEM (ITE_ID),
    FOREIGN KEY(SET_ID) REFERENCES SET_SETOR (SET_ID)
)

CREATE TABLE ITT_ITEM_TOMBADO (
    ITE_ID INT(20) PRIMARY KEY,
    ITT_DH_ALTERACAO DATETIME NOT NULL,
    ITT_DT_AQUISICAO DATE NOT NULL,
    ITT_COD_TOMBAMENTO_ANTERIOR INT(20),
    ITT_CD_USUARIO INT(9) NOT NULL UNIQUE,
    ITT_VALOR_ORIGINARIO FLOAT NOT NULL,
    ITT_DATA_NOTA DATE NOT NULL,
    CAT_ID INT(9) NOT NULL,
    ECI_ID INT(2) NOT NULL,
    FOREIGN KEY(ITE_ID) REFERENCES ITE_ITEM (ITE_ID),
    FOREIGN KEY(CAT_ID) REFERENCES CAT_CATALOGO_EFISCO (CAT_ID)
)

CREATE TABLE MEM_MEMBRO_COMISSAO (
    MEM_ID INT(7) PRIMARY KEY AUTO_INCREMENT,
    MEM_MATRICULA INT(7) NOT NULL UNIQUE,
    MEM_CPF INT(11) NOT NULL UNIQUE,
    MEM_NOME_COMPLETO VARCHAR(40) NOT NULL,
    MEM_EMAIL VARCHAR(40) NOT NULL,
    CAR_ID INT(3) NOT NULL,
    COM_ID INT(10) NOT NULL,
    FOREIGN KEY(CAR_ID) REFERENCES CAR_CARGO (CAR_ID),
    FOREIGN KEY(COM_ID) REFERENCES COM_COMISSAO_DO_PROCESSO (COM_ID)
)

CREATE TABLE ECI_ESTADO_CONSERVACAO_ITEM (
    ECI_ID INT(2) PRIMARY KEY AUTO_INCREMENT,
    ECI_ESTADO_DESCRICAO VARCHAR(40) NOT NULL
)

CREATE TABLE ITL_ITEM_LOCADO (
    ITE_ID INT(20) PRIMARY KEY AUTO_INCREMENT,
    ITL_NOME_EMPRESA_LOCADORA VARCHAR(40) NOT NULL,
    FOREIGN KEY(ITE_ID) REFERENCES ITE_ITEM (ITE_ID)
)

ALTER TABLE RES_RESPONSAVEL ADD FOREIGN KEY(CAR_ID) REFERENCES CAR_CARGO (CAR_ID)
ALTER TABLE INV_INVENTARUAL_ANUAL ADD FOREIGN KEY(COM_ID) REFERENCES COM_COMISSAO_DO_PROCESSO (COM_ID)
ALTER TABLE CONTEM ADD FOREIGN KEY(ITE_ID) REFERENCES ITT_ITEM_TOMBADO (ITE_ID)
ALTER TABLE DES_DESCARGA ADD FOREIGN KEY(COM_ID) REFERENCES COM_COMISSAO_DO_PROCESSO (COM_ID)
ALTER TABLE INC_INCLUSAO ADD FOREIGN KEY(COM_ID) REFERENCES COM_COMISSAO_DO_PROCESSO (COM_ID)
ALTER TABLE ITT_ITEM_TOMBADO ADD FOREIGN KEY(ECI_ID) REFERENCES ECI_ESTADO_CONSERVACAO_ITEM (ECI_ID)
